name: fcm_push
description: A Dart interface to Firebase Cloud Messaging (FCM) for Android and iOS
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-fcm-push

version: 1.2.7

environment:
  sdk: ">=2.0.0 <3.0.0"

# Add the bin/packages.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  fcm-push:

dependencies:
  args: ^1.5.0
  yaml: ^2.1.0

  firebase: ^5.0.0

  validate: ^1.7.0

  tuple: ^1.0.0

  http_utils: '>=1.6.0 <2.0.0'

  ansicolor: ^1.0.0

  logging: '>=0.11.3 <1.0.0'

  path: '>=1.6.0 <2.0.0'

  http: '>=0.11.3 <1.0.0'

  console_log_handler: '>=1.1.0 <2.0.0'

dev_dependencies:
  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any


